version: 2

aliases:
    - &restore_cache
        keys:
            - cget-{{ arch }}-{{ checksum "requirements.txt" }}
    - &install_dependencies
        name: Install Dependencies
        command: ./init.sh
    - &save_cache
        key:
            cget-{{ arch }}-{{ checksum "requirements.txt" }}
        paths:
            - "cget"
    - &build_from_source
        name: Build from source
        command: mkdir release && cd release && cmake .. && make
    - &run_tests
        name: Run Tests
        command: ./release/tests/GarlicConfigTest


jobs:
    test-linux:
        docker:
            - image: peymanmo/many_x64
        steps:
            - checkout
            - restore_cache: *restore_cache
            - run: *install_dependencies
            - save_cache: *save_cache
            - run: *build_from_source
            - run: *run_tests


workflows:
    version: 2
    pr-checks:
        jobs:
            - test-linux
